name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update major version tag
        uses: richardsimko/update-tag@master
        with:
          tag_name: v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
