name: "tests"
on:
  pull_request:
    types: [push, assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to test app
      uses: ./
      with:
        PAGELY_DEPLOY_DESTGELY_DEPLOY_DEST: "/httpdocs/test"
        PAGELY_INTEGRATION_SECRET: ${{secrets.TEST_TOKEN}}
        PAGELY_INTEGRATION_ID: ${{secrets.TEST_INTEGRATION_ID}}
        PAGELY_APP_ID: ${{secrets.TEST_APP_ID}}
        PAGELY_WORKING_DIR: "$GITHUB_WORKSPACE/test-assets"
    - name: Create a status check
      uses: LouisBrunner/checks-action@v0.1.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Integration Test
        conclusion: ${{job}}
