name: "tests"
on:
  pull_request:
    push:
      branches:
        - master
        - 'releases/*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create test artifact
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: test-assets
    - uses: ./
      with:
        deploy-url: ${{ secrets.TEST_DEPLOY_URL }}
        files: "test-assets/**"
        dest: /httpdocs
